### ISSUE TITLE
ResetOverrides

### ISSUE THREAD

**Issue by mdesoto** [sergebezborodov/sphinx-yii#3]
This may be a problem with my setup, but I was having trouble getting the extension to work due to line 426 in ESphinxConnection:

$this->sphinxClient->ResetOverrides();

Commenting the line out allows the extension to work. A quick check of the SphinxClient docs on php.net and there's no mention of SphinxClient::ResetOverrides. I'm using the latest version of the client, released in April 2013.

So this may be something, it may be nothing. I've literally just begun using Sphinx, and so forgive my ignorance if I'm missing something obvious.

**Comment by sergebezborodov** [comment]
Thank you for comment, I'll check it in days, sorry for long delay

**Comment by sergebezborodov** [comment]
i checked sphinx api version 2.0.9 and 2.1.1 - this function is exists. i'm using api from php file, not php module.
