### ISSUE TITLE
Composer error

### ISSUE THREAD

**Issue by Borales** [sergebezborodov/sphinx-yii#5]
Updating dependencies (including require-dev)
- Installing sergebezborodov/sphinx-yii (dev-master 4cf4b9d)
  Cloning 4cf4b9df5b07d3bcedadeb9e42198631488bb868

Writing lock file
Generating autoload files

```
  [RuntimeException]
  Could not scan for classes inside "common/lib/vendor/sergebezborodov/sphinx-yii/ESphinxConnection.php" which does not appear to be a file nor a folder
```

Скорее всего, `ESphinxConnection` класс нужно удалить из composer.json

**Comment by sergebezborodov** [comment]
Спасибо, сам еще не тестил с композером, внесу правки

On Thursday, September 19, 2013, Alexandr Bordun wrote:

> Updating dependencies (including require-dev)
> - Installing sergebezborodov/sphinx-yii (dev-master 4cf4b9dhttps://github.com/sergebezborodov/sphinx-yii/commit/4cf4b9d)
>   Cloning 4cf4b9dhttps://github.com/sergebezborodov/sphinx-yii/commit/4cf4b9df5b07d3bcedadeb9e42198631488bb868
> 
> Writing lock file
> Generating autoload files
> 
>   [RuntimeException]
>   Could not scan for classes inside "common/lib/vendor/sergebezborodov/sphinx-yii/ESphinxConnection.php" which does not appear to be a file nor a folder
> 
> Скорее всего, ESphinxConnection класс нужно удалить
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/sergebezborodov/sphinx-yii/issues/5
> .

## 

Sent from Gmail Mobile

**Comment by sergebezborodov** [comment]
updated config and readme, check it

**Comment by Borales** [comment]
@sergebezborodov https://packagist.org/packages/sergebezborodov/sphinx-yii
Состояние пакета в Packagist осталось на вчерашнем коммите.
В этой репе включен сервисный хук от Packagist?

**Comment by sergebezborodov** [comment]
обновил там пакет и настроил хук, 
для старой версии показывается отдельным тегом

**Comment by Borales** [comment]
@sergebezborodov нормально установилось, спасибо.
Только в `composer.json` есть дубликат - 2 записи `ESphinxMysqlConnection.php`

**Comment by sergebezborodov** [comment]
@Borales спасибо, поправил
